# This is the local development _config.yml file.
# Gulp now checks for this file.
# To run without Gulp:
#
# $ jekyll build --config _config.yml,_config.local.yml
#
url: http://localhost:4000
exclude: ['package.json', 'src', 'node_modules']
