environment:
  matrix:
    - RUBY_VERSION: 24
      nodejs_version: STABLE

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version

before_build:
  # Output useful info for debugging.
  - ruby --version
  - gem --version
  - node --version
  - npm --version

build_script:
  - ./build.cmd

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

test: off

artifacts:
  - path: _site/
    name: site
