environment:
  matrix:
    - RUBY_VERSION: 24

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%

before_build:
  # Output useful info for debugging.
  - ruby --version
  - gem --version
  - gem install bundler --no-document --force

build_script:
  - ./build.cmd

test: off

artifacts:
  - path: _site/
    name: site
